---
- hosts: 172.31.43.79
  become: yes
  tasks: 
    - name: i want to run linux command 
      command: hostname -f
      register: myresult

    - name: i want to display linux command output
      debug:
        msg: "{{myresult}}"  

    - name: i want to install wget
      apt:
        name: wget   
        state: present 
    
    - name: i want to install tree
      apt:
        name: tree  
        state: present

