---
- hosts: 172.31.43.79
  become: yes
  vars:
     myvar1: tree
     myvar2: wget
     myvar3: git
  tasks:
     - name: I want to display vars volume
       debug:
         msg: "{{myvar1}}"

     - name: I want to install package
       apt:
         name: "{{item}}"
         state: present
         when: ansible_os_family=="Debian" 
       loops:
         - "{{myvar1}}" 
         - "{{myvar2}}"   
         - "{{myvar3}}"