---
 # file:
  #     path: /home/ubuntu/tmper
   #    state: directory

# step 3:2 : download tomcat tar file in /tmp directory
- name: download tomcat tar file
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz
    dest: /home/ubuntu/tmper
    force_basic_auth: yes

# step 3:3 : /opt/tomcat directory on your server
- name: i want to create directory /opt/tomcat
  file:
    path: /opt/tomcat 
    state: directory

# step 3:4 : extract the archive file to /opt/tomcat
- name: i want to extract tomcat file 
  command:
    cmd: sudo tar xzvf /home/ubuntu/tmper -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE

         

